### ISSUE TITLE
Bei einigen ZDF Sendungen ist eine leicht bessere Qualität möglich

### ISSUE THREAD

**Issue by claell** [mediathekview/MSearch#38]
Dadurch, dass viele Abos nach der Umstellung der ZDF Mediathek erneut hinzugefügt wurden, ist mir beim erneuten Download aufgefallen, dass die Dateigrößen bei gleichen Sendungen abweichen.
Ein Blick in die Dateiattribute zeigt, dass sich hauptsächlich die Audioqualität verändert hat, während die Videobitrate leicht abweicht, mal nach oben, mal nach unten.

In der History habe ich die URLs von damals herausgesucht. Dabei ist mir aufgefallen, dass da noch eine andere Endung ist, mit der sich auch die aktuellen URLs modifizieren lassen.

Beispiele:
heute-show
Alte URL: http://nrodl.zdf.de.glcloud.net/none/zdf/16/10/161014_hsh_hsh/2/161014_hsh_hsh_2328k_p35v12.mp4
Neue URL: https://nrodlzdf-a.akamaihd.net/none/zdf/16/10/161014_hsh_hsh/2/161014_hsh_hsh_2256k_p14v12.mp4
Neue URL modifiziert: https://nrodlzdf-a.akamaihd.net/none/zdf/16/10/161014_hsh_hsh/2/161014_hsh_hsh_2328k_p35v12.mp4

Sketch History:
Alte URL: http://nrodl.zdf.de.glcloud.net/none/zdf/16/10/161007_sendung_ske/2/161007_sendung_ske_2328k_p35v12.mp4
Neue URL: https://nrodlzdf-a.akamaihd.net/none/zdf/16/10/161007_sendung_ske/2/161007_sendung_ske_2256k_p14v12.mp4
Neue URL modifiziert: https://nrodlzdf-a.akamaihd.net/none/zdf/16/10/161007_sendung_ske/2/161007_sendung_ske_2328k_p35v12.mp4

**Comment by xaverW** [comment]
ist drin, Pull angestoßen

**Comment by alex1702** [comment]
Nicht schliessen, erst wenn es in master und damit im nächsten release drin ist ;)

**Comment by xaverW** [comment]
da hat der merge nicht richtig funktioniert (verschobenen Zeile war dann doppelt), ist korrigiert

**Comment by claell** [comment]
Super, danke fürs Einbauen.
