### ISSUE TITLE
Gradle Build failed unter Windows

### ISSUE THREAD

**Issue by pidoubleyou** [mediathekview/MSearch#39]
Wenn ich unter Windows mit Gradle das Projekt baue, schlägt der Build folgenden Fehlern:

MSearch\src\main\java\mSearch\tool\FilenameUtils.java:205: error: unmappable character for encoding Cp1252
                if (c == 'Ã‚' || c == 'Ã€' || c == 'Ã…' || c == 'Ã?') {
                                                                                 ^
MSearch\src\main\java\mSearch\tool\FilenameUtils.java:211: error: unmappable character for encoding Cp1252
                } else if (c == 'Ä‡' || c == 'Ä?' || c == 'Ã§') {
                                                       ^
MSearch\src\main\java\mSearch\tool\FilenameUtils.java:213: error: unmappable character for encoding Cp1252
                } else if (c == 'Ä?') {
                                     ^
MSearch\src\main\java\mSearch\tool\FilenameUtils.java:229: error: unmappable character for encoding Cp1252
                } else if (c == 'Å‚' || c == 'Å?') {
                                                      ^
MSearch\src\main\java\mSearch\tool\FilenameUtils.java:245: error: unmappable character for encoding Cp1252
                } else if (c == 'â€?' || c == 'â€œ' || c == 'Â«' || c == 'Â»') {
                                         ^

**Comment by shoeper** [comment]
Folgendes könnte den Fehler beheben:

http://stackoverflow.com/a/32555356
