### ISSUE TITLE
ZDF JSON API

### ISSUE THREAD

**Issue by criztovyl** [mediathekview/MSearch#41]
mediathekview/mediathekview#120 gehört eher hier her.

**Comment by Nicklas2751** [comment]
Mittlerweile gehört das zu MServer. 

Ist der Task überhaput noch von benötigt?

**Comment by criztovyl** [comment]
Da hat sich so lange nix getan, ich denke das kann zu.

**Comment by criztovyl** [comment]
Oh, den Assign hab ich nicht geseh'n mal gucken ob da nen Fork u/o ne Branch rumluegt auf der sich was tut.
Ob der Task wiederrum benötigt wird weiß ich nicht.

**Comment by pidoubleyou** [comment]
ich hab im Branch zdf_hd angefangen, der noch auf dem master basiert. Als die Verschiebung in MServer anfing, habe ich erstmal abgewartet. Ich werde einen neuen Branch in MServer anfangen und die Änderungen hineinbringen.
Der Vorteil der Änderung wäre, dass die Zugriffe auf die ZDF-Daten über die JSON-API laufen und das komplizierte Parsen der HTML-Strukturen nicht mehr benötigt wird.

**Comment by criztovyl** [comment]
Soweit ich das im Code gelesen hab ist das letztendlich nur suchen nach Mustern, ganz ohne DOM (korregiert mich wenn ich mich irre).
Ich bin mir aber auch nicht sich ob @xaverW bei seiner Anpassung der Crawlers an die neue Mediathek nicht auch schon die neue ZDF API nutzt.

**Comment by pidoubleyou** [comment]
Dieser Issue betrifft mittlerweile MServer, deshalb dorthin verschoben und dieser Issue geschlossen.

[MServer/Issue#39](https://github.com/mediathekview/MServer/issues/39)
