### ISSUE TITLE
Das Crawling der ZDF-Mediathek + Sendung mit Geotargeting = (scheinbar) einige Probleme

### ISSUE THREAD

**Issue by zxsd** [mediathekview/MSearch#42]
h-ttp://zdfmediathk.sourceforge.net/forum/viewtopic.php?f=3&t=2226&start=51

Als Holtlink funzt obige URL nicht ... SF.net wurde ins github.com umgestaltet ...

**Comment by alex1702** [comment]
http://zdfmediathk.sourceforge.net/forum/viewtopic.php?f=3&t=2226&start=51

**Comment by xaverW** [comment]
die URLs sind mit aufgenommen
