### ISSUE TITLE
Issue Status (pl.) & Closing

### ISSUE THREAD

**Issue by zxsd** [mediathekview/MSearch#48]
Ein Issue offen lassen bis dessen Änderungen in einem Release/einer Version veröffentlicht wurden.  Bei "Closed" Issues/Beiträgen soll abzulesen sein, welche Version sie erst enthält.  Eine "Entwicklerversion" im vorigen Sinne des Wortes, soll dann als Beta-Test auch dienen.

Um die Übersicht fur Github-Besucher zu gewähren, Tags/Buttons wie "in Bearbeitung" und "Betriebsbereit" (also Alpha-Test erfolgreich absolviert) verwenden.

**Kontext**

https://github.com/mediathekview/MSearch/issues/42 ... und wohl auch andere Issues unter der Familie, "mediathekview".

Vor einigen Tagen wurde Quellentext das Crawler-Software vom **xaver_w** aktualisiert.  Bis diese Version in Betrieb ist, wird es von Anwendern (und vielleicht anderen) nicht prüfbar bleiben.  <Edit> Ich habe soeben gemerkt, daß das Update jetzt (12. Nov. 2016) im Betrieb ist.

**Comment by alex1702** [comment]
Hast recht ich werde da mal noch ein paar Labels einführen.

**Comment by criztovyl** [comment]
Dieser Issue betrifft eher MediathekView im allgemeinen als nur MSearch, ich schließe hier und ersetze durch mediathekview/mediathekview#148.
