### ISSUE TITLE
versions.properties

### ISSUE THREAD

**Issue by alex1702** [mediathekview/MSearch#52]
Da diese Dateien dauernd verändert werden wenn ich MServer lokal baue, würde ich diese gerne entfernen und später gucken wie man das besser umsetzt.

**Comment by xaverW** [comment]
kein Problem, war nur eine Info.

**Comment by alex1702** [comment]
ok gut.

**Comment by criztovyl** [comment]
Wenn du die `version.properties` löscht, setzt das dann nicht [mSearch.tool.Functions#getBuildNr](https://github.com/mediathekview/MSearch/blob/master/src/main/java/mSearch/tool/Functions.java#L150) außer Gefecht?

**Comment by xaverW** [comment]
stimmt, kommt eine Fehlermeldung dann:

* Fehlernr: 807293847
* Exception: Can't find bundle for base name version, locale de_DE
* Fehler(MSearch): Functions.getCompileDate
und
* Fehlernr: 134679898
* Exception: Can't find bundle for base name version, locale de_DE
* Fehler(MSearch): Functions.getBuildNr

das muss man dann auch raus nehmen.

**Comment by alex1702** [comment]
sollten wir als hot fix entwickeln.

**Comment by xaverW** [comment]
ich frage mich, ob das mit der Nummerierung der Releases (für die lib) wirklich gut ist. Ich hatte anfangs auch 3stellige Versionsnummern. (ist das jetzt 3.0.0 oder noch 2.2.0, ..). Wäre es nicht sinnvoller eine Versionsnummer für alle Teile des Programms (Server, lib, gui) zu nehmen (einstellung wie bisher), die wird mit jeder Veröffentlichung von MView hochgezählt. Und zusätzlich gibts eine ReleaseNr. Die angezeigte Versionsnummer ist dann Version-ReleaseNr.
Die ReleaseNr sollte dann natürlich nicht wie bis jetzt bei jedem build eines Entwicklers hochgezählt werden sondern nur von Alex beim Bauen eines Release. Gerade der Server wird ja laufend geändert.
Und mit der ReleaseNr könnte man auch schön sehen, welche "Version" läuft. Die Wird ins Log geschrieben und beim Start ausgegeben und die kann sich dann auch unterscheiden zwischen den Teilen des Projekts (lib, server, ..)
Ein Vorschlag

**Comment by xaverW** [comment]
und wenn nicht, dann sollte die jetzige Versionsnummer dann aber im Programm angezeigt werden (und im log) statt der bisherigen?

**Comment by alex1702** [comment]
ja also angepasst werden muss das jetzt eh noch alles. ich bervorzuge die 3stellige. alle änderungen die dann gemacht werden wie z.b. ah zdf hat was geändert wird dann immer ein hotfix, da es schnell rein sollte. und änderungen die nicht so eine dringlichkeit haben und kompatibel bleiben mit mServer und mediathekview die bekommen eine erhöhung in der zweiten stelle (dritte fängt dann wieder bei 0 an).
Wenn wir aber größere änderungen machen, die eine anpassung auch in mediathekview und oder mserver beinhaltet, dann wird die erste ziffer erhöht. 
Also ich hab kein problem bei einem versionsupdate/release irgendwo in einer datei eine nummer zu erhöhen wir müssten uns nur einigen wie wir das machen. z.b. gibts jetzt eine versionsnummer in der build.gradle, eventuell kann man die ja irgendwo hinschreiben lassen oder umgekehrt es gibt eine VERSIONS datei wo ich die version rein schreibe und gradle holt die sich da mit raus. 
Im moment klappt das System mit den releasen auch noch nicht so ganz wie gewünscht. es gibt nur den sourcecode und da sind auch alte datein dann noch drin. Es fehlt noch ein build, bzw. travis muss noch das was lokal schon geht im build ordner mit der zip und dem tar.gz dass muss noch irgendwie deployed werden.

**Comment by xaverW** [comment]
die Versionsnummer habe ich auch gerade gesucht: die steht im build.gradle, da wird das Programm aber nicht rankommen. die Nummer müsste irgendwo hin wo sie das Programm erreicht. Im Prinzip ist die ganze Nummerierung ja nur eine Formsache aber ich hab es irgendwann aufgegeben, mir immer überlegen zu müssen: 2.0.4 oder 2.1.0 oder vielleicht doch schon 3.0.0.

Es sollte auf jeden Fall möglich sein, im log die Release unterscheiden zu können, das war seeeehr hilfreich. (vor allem auch bei der Gui-Entwicklung da die Testet immer unterschiedliche "Versionen" verwenden)

**Comment by alex1702** [comment]
Ja also ich will es auch nicht aufgeben eine versionsnummer irgendwie im programm zu haben. eventuell packt man aber lieber auch die Versionsnummer mit in den code, dann hat man keine lästigen Datein für sowas. also irgendwie eine version.java oder info.java wo sie prägnant steht, dann kann man auch gleich implementieren mit der komandozeilen übergabe -v z.b. die version auszugeben. (zusätzlich wohlgemerkt)
dann würde ich auch eine extra VERSIONS datei idee verwerfen und es bleibt dann bei build.gradle, die eine .java und beim releasen selbst. damit würde ich zurecht kommen.

**Comment by Nicklas2751** [comment]
Aktuell wird die versions.properties und co doch beim bauen durch Gradle generiert?. Ich würde auch 3 stellige bevorzugen. Wegen dem hochzählen kenn ich das so: die letzte Stelle ist für Hotfixes, die 2. für normale realeres und die erste für größere realeres die mit dem vorherigen nicht kompatibel sind.
Beispiel 2.0.0 hat nen Bug dann kommt zum fixen: 2.0.1
Wenn alex dann ein neues Feature einbaut wird es 2.1.0 und wenn wir zB die UI komplett austauschen oder das Dateiformat der Konfigurationsdatein ändern wird es: 3.0.0 usw.



Von meinem iPhone gesendet

**Comment by xaverW** [comment]
> Aktuell wird die versions.properties und co doch beim bauen durch Gradle generiert?.

nein, nicht in msearch, das stand noch drin:

> VERSION=13 .....

> Beispiel 2.0.0 hat nen Bug dann kommt zum fixen: 2.0.1

dann können aber einzelne Releases nicht unterschieden werden

-v geht jetzt schon

es muss irgendwas sein, dass automatisch funktioniert, sonst sind Fehler vorprogrammiert. Wenn gradle die Versionsnummer in eine .properties Datei schreibt dann könnte das Programm sie auslesen und es würde auch die beim Bau des Release vergebene Nr angezeigt. Und hochzählen läuft nicht automatisch, das machst nur du beim Build eines Release, dann hast du auch das Problem mit den ständig geänderten .proberties Dateien weg

**Comment by xaverW** [comment]
> Wegen dem hochzählen kenn ich das so: die letzte Stelle ist für Hotfixes, die 2. für normale realeres und die erste für größere realeres die mit dem vorherigen nicht kompatibel sind.

machen viele Projekte so, es wechseln aber immer mehr zu einfachen Versionsnummer (Firefox, aktuell 50.0)

erklärt das Verfahren, sagt aber nicht warum es besser ist, als einfach hochzuzählen, bei jeder Veröffentlichung der GUI vorne, bei jedem Release nach dem Komma

aber egal wie, das Programm sollte es anzeigen und dazu muss es irgendwie rankommen.

**Comment by Nicklas2751** [comment]
Die Version im Gradle ist soweit fest und sollte vor jedem Realese hündisch erhöht werden. Dann sollte Gradle aber bereits die Version.properties und co generieren und richtig befüllen.



Von meinem iPhone gesendet

**Comment by xaverW** [comment]
in build.gradle ists schon entfernt, die müsste wieder zurückgesetzt werden.
wenn man nur das build-Datum entfernt, würde sich Version.properties beim normalen build nicht ändern und das problem mit den geänderten Version.properties wäre weg und das Programm könnte doch die Versionsnummer auslesen.

**Comment by Nicklas2751** [comment]
Ja das sollte gehen. Dann wird vom Entwickler vorm Realese (bzw. Alex) im Gradle die Version erhöt und beim bauen erzeugt gradle dann die version.properties welche die aktuelle Version beinhaltet so, dass es ausgelesen werden kann.

**Comment by alex1702** [comment]
ne das macht kein sinn, dass entwickler die version erhöhen.

**Comment by alex1702** [comment]
kurze verständnis frage landete die versions.properties in der jar?

**Comment by xaverW** [comment]
die Versionsnummer (egal wie die jetzt aussieht) sollte also nicht automatisch hochgezählt werden. Das machst nur du wenn du ein neues Release baust.

landet im jar

**Comment by xaverW** [comment]
wichtig wäre aber, dass jedes release auch eine eigene Nr. hat um sie zu unterscheiden.

**Comment by alex1702** [comment]
ja ok dann kann das wieder in abgespeckter version rein.

**Comment by alex1702** [comment]
ja das wird auch so sein. also es wird nie ein release mit der gleichen version geben.

**Comment by Nicklas2751** [comment]
@Alex ich denke es ist am besten die Version händisch vor dem bauen des realeres hoch zu ziehen und dann damit zu bauen und zu testen ob auch das Projekt so noch bauen kann usw. 

Beispiel:
Version 2.1.2 soll veröffentlicht werden. Du erstellst zu erst den realese branch vom aktuellen Master und erhöhst nun die Versionsnummer und baust das Projekt erstmal lokal und behebst eventuell auftretende Fehler. Wenn alles passt wird davon dann ein Tag erstellt und travis tut den Rest. Bzw wird in Master gemerged und dann tag.




Von meinem iPhone gesendet

**Comment by criztovyl** [comment]
Ich würde die Version nicht vollkommen händisch erhöhen, eher nen Gradle-Task dazu machen, á la `gradle release`.

**Comment by alex1702** [comment]
könnte man noch drüber nachdenken. falls man auf die version in der build.gradle zugreifen könnte wäre es noch praktischer.

**Comment by xaverW** [comment]
verzeih :) wenn ich nochmal nachbohre: wenn die Versionsnummer schon 3-Stellig sein soll dann **bitte** wenigstens die erste Stelle bei allen Programm gleich machen. Die Programme gehören doch zusammen und hängen auch voneinander ab. Das verwirrt doch nur: "brauch ich für die Gui 13.0.1 die lib in Version ab 2.1.0 oder 2.2.0 ??".

Gui 13.xx läuft mit lib 13.xx
usw.

und die Versionsnummer bei der Gui kann nicht 2.0.0 werden, die gabs schon mal.
ich würde vielleicht auf Grund des neuen Starts gleich mit 14 anfangen.

**Comment by xaverW** [comment]
bleibts jetzt bei bei version.properties oder soll ich noch mit den Änderungen warten?

**Comment by alex1702** [comment]
Es sollte so sein, dass die GUI immer mit der neusten Version läuft. Deswegen soll die Bibliothek ihre eigene Versionierung bekommen. Da normalerweise die Bibliothek immer mit ausgeliefert wird sollte man da garnicht in die Bedrullie kommen zwischen Versionen aussuchen zu müssen. Wenn Version 14 von der gui auch mit der aktuellen Version der Bibliothek läuft will ich nicht auch immer die Version von der Bibliothek hochziehen müssen, nur damit die dann die gleiche Version haben.

Also die versions.properties datei kommt jetzt wieder rein in abgespeckter version es kommt nur die version in die datei, damit das fertig gebaute Programm die auslesen kann und man immer eine referenz hat.
Die Datei kommt wieder an den ursprünglichen Ort und wird nur von mir bei einem Release abgeändert.
Eventuell wird mal das aktualisieren der Datei durch einen gradle task erledigt.

**Comment by alex1702** [comment]
Das ganze kannst du als hotfix ausführen.

**Comment by Nicklas2751** [comment]
Ich habe schon in einem passenden hotfix branch angefangen bin nur noch nicht fertig geworden. ;)



Von meinem iPhone gesendet

**Comment by xaverW** [comment]
ich habe die Programmänderungen gemeint, kommen die noch?

**Comment by alex1702** [comment]
Bin mir grad nicht sicher was du mit Programmänderungen meinst. Muss noch was am programmcode angepasst werden?

**Comment by xaverW** [comment]
das Datum fehlt ja jetzt

**Comment by alex1702** [comment]
achso und das wurde mit angezeigt?
dann muss diese anpassung natürlich auch noch vorgenommen werden im programm.

**Comment by xaverW** [comment]
Fehlernr: 807293847
    Exception: Can't find bundle for base name version, locale de_DE
    Fehler(MSearch): Functions.getCompileDate

s. oben

**Comment by alex1702** [comment]
okok dann sollte das noch angepasst werden. möchtest u das machen? kannst einfach im hotfix branch weiter dran arbeiten.

**Comment by xaverW** [comment]
Ok

**Comment by criztovyl** [comment]
Ich finde die Version sollte vollkommen unabhängig vom Buildskript sein, das ist statisch, die Version nicht.

**Comment by criztovyl** [comment]
Die Version steht in der `version.properties`, soweit interessiert das Gradle auch nicht, die ladet einfach nur mit in der JAR.
Was Gradle dann aber gerne tun kann, ist der Task zu erhöhen der Version.

**Comment by Nicklas2751** [comment]
Ein Build Skript ist doch nix statisches. Es steuert immerhin den Build und da gehört die Version dazu. Beispiel beim dependency Management lesen Maven und Gradle die Version aus der pom.xml bzw dem build.gradle. Das komplette dependency Management interessiert sich nicht für versionen außerhalb dieser datein. Und da wir die Version zwangsweise im buildskript brauchen welches die version.properties generiert brauchen wir die version.properties nicht im git da diese ja generiert werden kann. Und bei einem realese ist es ja dann Teil vom hat und damit verfügbar. Ich sehe und kenne keine andere Lösung als die Version im Skript zu haben. Außer wir wollen bei jeder Versions Änderung mehr als eine Stelle anpassen müssen.

**Comment by Nicklas2751** [comment]
Dann muss die Version in der properties Datei und im Gradle geändert werden. Es ist deutlich einfacher wenn die Version im Gradle ist wo wir sie eh auf jedenfall brauchen und das version.properties welches wir nur im JAR brauchen einfach generieren.

Es ist absolut sinnlos eine komplett generierbare Datei die nur während des Builds benötigt wird ins git einzuchecken.

**Comment by criztovyl** [comment]
Hm, okay, im Bezug auf den Code ist's ein Buildskript schon statisch. Es ändert sich nur wenn sich der Buldablauf ändert. Die Version ist nur ne Eingabevariable, kein Ablauf.

Den Ansatz die `version.properties` bei jedem Build neu zu generieren nicht besonders klug. Es ging ja hauptsächlich darum das sie sich bei jedem Build verändert hat, weil BuildNr und Datum verändert wurden. Da das beides jetzt aber raus ist, ändert sie sich nicht mehr.

Und vollkommen generierbar ist sie eben nicht, sie verändert sich ja nur bei einem Release oder Hotfix und ist eins höher als die vorher. Und Gradle beizubringen die letzte Version zu suchen ist unnötig, daher muss diese Information mit ins Git.

Natürlich lässt sich die Version händisch in der `build.gradle` anpassen, aber das bringt nur Arbeit mit sich, die es vorher so nicht gab.

**Comment by Nicklas2751** [comment]
Gradle braucht für ein ordentliches dependency mangegement die passende Version im Build Skript hinterlegt ein auslesen und erhören ist absolut sinnlos und die Erzeugung der Datei kostet effektiv keine Ressourcen und die Datei wird Lokal erzeugt wenn sie gebraucht wird. Wenn sie schon erzeugt wurde wird sie nur angepasst. Aber im git ist sie sinnlos.

**Comment by Nicklas2751** [comment]
Bau das Projekt am besten mal Lokal durch dann siehst du was ich meine. Gucks dir mal an und lies dir mal dependency Management mit Gradle durch.

**Comment by alex1702** [comment]
Ich gebe Nicklas recht, die Datei wird nicht direkt gebraucht, da sich gradle die selber baut wenn sie benötigt wird (effektiv bei einem build). Da die version im build.gradl eh angepasst werden muss macht es nur sinn die version aus dieser abzuleiten und in die version.properties einzutragen.

**Comment by criztovyl** [comment]
Abhänigkeiten sind nicht dynamisch. Die sind so, wie sie woauchimmer festgelegt sind, das hat nichts mit der Version zu tun, das ist eine rein kosmetisch Gelegenheit.
Und wenn sich die Abhängigkeiten ändern, wird das woauchimmer geändert, wird commited und ist somit immer passend zu der Version die grad' ausgecheckt ist.

**Comment by alex1702** [comment]
Es wird in der build.gradle geändert.

**Comment by criztovyl** [comment]
Und die Version interessiert Gradle ja nur, wenn es die erhöhen soll. Ansonsten packt's die `version.properties` stupide in die JAR.

**Comment by Nicklas2751** [comment]
Nein Ebene nicht. Gradle braucht die Version weil auch zB MSearch selbst eine dependency ist. Die Version.properties wird nur im jar gebraucht sonst nirgends.

**Comment by criztovyl** [comment]
Wenn du MSearch als Abhänigkeit so einsetzt wie das derzeit abläuft, das MSearch einfach nur in `../MSearch` gesucht wird, interessiert sich Gradle für die Version nicht sondern baut das was da rumliegt.

Die Version wird dann erst wieder Spannend wenn du die Lib in ne JAR packst, dann muss Gradle wissen welche das ist. Aber die ist dann variabel (eins höher als vorher) und Variablen speicherst du nicht im Buildskript.

**Comment by criztovyl** [comment]
Okay, es gibt eine Möglichkeit, bei der ich einer vollständig generierten `version.properties` würde: Wenn die Version sich auf's Git bezieht, á la `git describe`.

**Comment by Nicklas2751** [comment]
Wieso willst du so viel Aufwand für die properties Datei brauchen die eigentlich nur gebraucht wird um den User eine Version anzuzeigen? Sie hat keinen weiteren nutzen und dient nur als Medium zum anzeige der Version. Die Buildnummern wurden abgeschafft. Der User braucht keine Build exakte Nummer. Ein 3.0.0 oder Version 13 ist vollkommen ausreichend und das wird via dem Build.gradle hündisch eingestellt. All deine Vorschläge machen uns allen nur unnötige Arbeit für eine grundsätzlich fast sinnlose Datei. Keiner deiner Gründe beschrieb die aktuelle Situation. Ich habe das Gefühl du verwechselst die properties Datei mit etwas anderem. So wie wir aktuell dank Gradle arbeiten können hat sie keinen Wert. Sie ist eine Altlast die wir entfernen können und du klammerst dich künstlich daran. Es sind mit voller Absicht keine konkreten Informationen wie buildnummer oder Datum enthalten. Alles was interessiert ist die Version. Und die ist im Gradle. Nicht im git und nicht in der properties Datei.

**Comment by criztovyl** [comment]
0. Bei meinem Vorschlag kommt **keine extra Nummer dazu**? oO Als Version `git-describe` zu nehmen ist so das fehlerunanfälligste was es gibt.
0. Mit diesen Ansatz **verschwindet** die `version.properties` auch **aus dem Git**!
0. Ich finde auch **nicht**, das das jetzt besonders viel Aufwand ist, sogar **weniger**! Niemand braucht hier außerhalb von Git eine Version pflegen, das ist doch ein riesiger Vorteil?
0. Es ist nicht „nur” für den User, die ist für alle. Stell dir bspw vor, das mit nem Hotfix (bspw `13.1.0`) ne Verhaltensänderung reinkommt, dann musst du den Nutzer nicht immer Fragen 13 mit oder ohne Hotfix? (Er sagt dir einfach `13.0.0` oder `13.1.0` schon beim Bugreport/Ticket/wasauchimmer).
0. Ich sehe jetzt auch keinen besseren Weg, MV vernünftig die Version mitzugeben, so als Resource ist das schon okay.

Und die BuildNr ist entfernt, über das Datum lässt sich noch diskutieren. Ich persönlich würd's als wirklich rein kosmetische, unnötige Info mit reinneh'm, ist einfach ne schicke Info.

**Comment by Nicklas2751** [comment]
Es wird weiterhin die Version im Build.gradle benötigt da wir die immer brauchen. Dadurch kommt durch die git Version eine zusätzliche Versionsnummer hinzu.

**Comment by criztovyl** [comment]
Wozu brauchst du die fest in der `build.gradle` eingetrage Version denn? Die lässt sich doch aus `git-describe` ableiten?

**Comment by criztovyl** [comment]
Ist das euer Ernst?

**Comment by criztovyl** [comment]
Ich bin hier dabei um Arbeit zu verwinfachen, nicht um sie zu verkomplizieren. Wenn es einen wirklich triftigen Grund gibt, eine statische Version in der `build.gradle` zu haben, kann ich mich dem Beugen, aber das ist so nicht der Fall, wenn die Version sich aus `git-describe` ableiten lässt.

**Comment by alex1702** [comment]
Ja ist mein ernst, ich möchte nicht die Ableitung aus git. Wenn jemand das zip runter lädt, hat er euch kein git dadrin und die Version kann nicht mehr aus git abgeleitet werden. 
Und ich sehe auch kein Problem darin, die eine Variable in einem build skript immer anzupassen. Eventuell kann man später mal als verbesserung einbauen, dass die Version aus einer extra Datei ausgelesen wird von gradle, aber da sehe ich grad nicht unbedingt eine Notwendigkeit.

**Comment by criztovyl** [comment]
Das ist ein Argument, das ist versteh'n kann, kam aber nie so zur Sprache.
