### ISSUE TITLE
ORF: Doppelte Einträge

### ISSUE THREAD

**Issue by simon04** [mediathekview/MSearch#53]
Die Sendungsliste für den ORF enthält viele Einträge doppelt. Die Einträge Zeit und Webseite sind jeweils ident.

![2016-11-14-19-31-26-001](https://cloud.githubusercontent.com/assets/782446/20277486/1ac8b6dc-aaa1-11e6-9b3f-757d11c29d78.png)

**Comment by xaverW** [comment]
da ist ein weiterer variabler Teil in der URL dazugekommen:

http://apasfpd.apa.at/cms-worldwide/online/a0be159229f7c5908793c8239e1ae729/1478200261/2016-10-31_0600_tl_02_ZIB-6-00_Clinton--Schuet__13892821__o__1505545961__s13902078_8__ORF2HD_06001822P_06012811P_Q6A.mp4
http://apasfpd.apa.at/cms-worldwide/online/9c05369bec8e4602cedbe0a17d4c019d/1478239784/2016-10-31_0600_tl_02_ZIB-6-00_Clinton--Schuet__13892821__o__1505545961__s13902078_8__ORF2HD_06001822P_06012811P_Q6A.mp4

und deswegen werden sie doppelt in die Liste einsortiert

online/a0be159229f7c5908793c8239e1ae729/1478200261/2016-10-31
online/9c05369bec8e4602cedbe0a17d4c019d/1478239784/2016-10-31

der erste Teil wird bereits ausgeblendet

**Comment by xaverW** [comment]
muss mich korrigieren (der 2. variable Teil wird auch schon ausgeblendet):

es gibt einen kleinen Unterschied im Thema der dafür verantwortlich ist (Bindestrich, auch auf dem Foto zu sehen):
Sender - Thema - Titel
ORF  Burgenland heute	"Weißes Wasser"
ORF	 Burgenland-heute	"Weißes Wasser"
ist der Index nach dem Verglichen wird:
arr[FILM_SENDER].toLowerCase() + arr[FILM_THEMA].toLowerCase() + DatenFilm.getUrl(this);

**Comment by simon04** [comment]
Fix in cc02b709019f6f5f5c1c22bd0acaad32a1c912d7.
