### ISSUE TITLE
Deploy-Key ändern

### ISSUE THREAD

**Issue by alex1702** [mediathekview/MSearch#54]

**Comment by criztovyl** [comment]
(https://github.com/mediathekview/MSearch/commit/995849f5081aa37972c381c002c29d74beae99a9)

**Comment by alex1702** [comment]
Lol da wurde mehr geändert als sollte voll dämlich ob das an gedit liegt? Oder hat da jemand echte tabs genommen? Hmm

**Comment by criztovyl** [comment]
`.yml` geht eig. mit echten Tabs gar nicht.
Aber ob 2 oder 4 Leerzeichen differenziert oft.

**Comment by alex1702** [comment]
Ok mal gucken.

**Comment by criztovyl** [comment]
Soweit ich das hier sehe scheint's 2 vs 4 zu sein.

**Comment by alex1702** [comment]
Wie verlinkst du den commit? Gibts da eine einfache Methode?

**Comment by criztovyl** [comment]
Einfach den Link einfügen, GitHub macht das dann schick :)
Ansonsten kannst du in Commits bspw. #54 hinzufügen & dann taucht er hier auch auf.

**Comment by alex1702** [comment]
Ok perfekt dann weiß ich das fürs nächste mal.
