### ISSUE TITLE
Debug in NetBeans with Commandline Args

### ISSUE THREAD

**Issue by xaverW** [mediathekview/MSearch#60]
habe das Problem dass ich in msearch nicht die GUI zum debuggen erreiche. Muss immer das in build.graddle einfügen, dann wird beim debuggen der Parameter übergeben:

```
task(debug, dependsOn: 'classes', type: JavaExec) {
    main = 'mSearch.Main'
    classpath = sourceSets.main.runtimeClasspath
    args '-gui'
    debug true
}
```

kann man das dauerhaft einfügen? Gibts einen besseren Weg?
Gleiches wäre auch in MView/MServer interessant für den Pfad zum KonfigVerzeichnis

**Comment by alex1702** [comment]
Ich denke das kann man hinzufügen.

**Comment by xaverW** [comment]
ist drin und geht.
