### ISSUE TITLE
Ziel noch im Auge?

### ISSUE THREAD

**Issue by xaverW** [mediathekview/MSearch#63]
wenn ich mir den aufwändigen Build-Prozess ansehe und die Diskussionen darüber, habe ich immer mehr das Gefühl, dass schön langsam das Ziel aus den Augen verloren geht. Mir kommt das so vor: Ich kauf mir ein Haus und diskutiere Wochen lang darüber, wie ich den Keller fliesen will. Übersehe dabei aber, dass das Dach regelmäßig gepflegt werden muss, damit es nicht rein regnet.

Ich habe in Netbeans auf "clean and build" geklickt und mit ein paar Scripten ist alles zu GitHub und zu den Servern hoch geladen worden. Die liefen dann mit der neuen Version und die User konnten sie einfach laden und testen. Ist vielleicht nicht alles nach Leerbuch und ergab wahrscheinlich auch keine so schöne Git-History, hat aber die 8 Jahre gut funktioniert.

Der User möchte eine fehlerfreie Filmliste und ein Programm mit dem er klar kommt.

Bei dem Aufwand der für den Build-Prozess getrieben wird, frage ich mich schon, wo da noch die Zeitersparnis sein soll und ob die viele Arbeitszeit an der richtigen Stelle verbraucht wird.

Das Zitat von Erich Kästner habe ich heute im Forum gelesen:
**"Je üppiger die Pläne blühen, desto verzwickter wird die Tat!"**

Vielleicht eine Idee wert.

**Comment by Nicklas2751** [comment]
Ich finde du hast grundsätzlich recht aber ich denke auch, dass besonders das einführen von Gradle und Travis sich jetzt schon gelohnt hat. 

Mir fällt jedenfalls dadurch das Arbeiten um einiges leichter und es geht schneller. 
Es fehlt eine Libary wie z.B. Log4J? Kein Problem ist mit einer änderung im Gradle drin. Ich will das Programm unter Windows Testen und direkt einen Fehler beheben? Kein Problem gradle baut auch unter Windows. Ich habe vergessen eine Datei mit ein zu checken? Travis sagts mir spätestens beim nächsten push.

**Comment by xaverW** [comment]
> Kein Problem gradle baut auch unter Windows.

das ging vorher auch alles, da alle Abhängigkeiten in GitHub dabei waren.

Wenn ich die MLib hätte anlegen wollen:
- Ordner MSearch kopieren
- in netBeans als neues Projekt öffnen und umbenennen
- das einfache!! buildscript anpassen
- in MView die Abhängigkeit auv MLib drehen

nach 1/2h hätte man mit dem Arbeiten am Source anfangen können.

hier ist zwar mal MLib in GitHub angelegt worden aber jetzt wartet der eine auf den anderen, den komplizierten build-prozess einzurichten, damit man damit arbeiten kann.

Ihr sollt hier doch nicht mit einer Masterarbeit euren Prof beeindrucken und zeigen was ihr drauf habt, sondern es sollte ein gutes Programm für den User herauskommen. Wer arbeitet denn wirklich am Programmsource? Der Aufwand der hier die letzten Wochen betrieben wurde, den hatte ich die ganzen 8 Jahre nicht.

**Comment by Nicklas2751** [comment]
Ich denke nicht dass #45 jetzt am build skript hängt. Es macht nur einfach aktuell niemand was daran. Es gibt weder einen branch mit angefangener arbeit bzw. bereits umgezogenen Dateien noch sonstiges. Jemanden der um Hilfe zwecks des Build skriptes dafür bittet habe ich auch noch nicht gesehn.

Das für dich das ant build skript einfach war ist klar und es unter netbeans einfach funktionierte. Mit eclipse und am besten noch unter windows wo keine .sh Dateien ausgeführt werden können (ich ereinnere da an pre- und post-build.sh) sähe das schon anders aus. Aktuell müsste man für den Umzug eigentlich auch nur MSearch kopieren im build Skript den Namen von MSearch auf MLib ändern und könnte dann mit den Source Arbeiten anfaangen. Nur es macht halt im Moment niemand, jedenfalls nicht öffentlich sichtbar.

Zusammengefasst auch da sehe ich kein Problem an der neuen Infrastruktur, der Hinweis dass es aber nicht voran geht ist gut ich. Gucks mir evtl. heute noch spätestens morgen mal im Detail an. ;)

**Comment by xaverW** [comment]
> Jemanden der um Hilfe zwecks des Build skriptes dafür bittet habe ich auch noch nicht gesehn.

genau das habe ich doch eben gemacht.

Legt es "an" und kopiert den Source 1:1 von hier rein und dann muss noch MView darauf umgebogen werden. Dann kann man damit anfangen alles was MView nicht braucht, rauszuschmeißen.

Dann wird MSearch um den "Server" erweitert.

So war es doch auch gedacht??

**Comment by criztovyl** [comment]
Also das Bauen funktioniert für mich ohne Probleme.

(Alle Projekte müssem in einem gemeinsamen Ordner liegen)

0. Ins Projekt gehen
0. `./gradlew build`
