### ISSUE TITLE
Feature: ZDF -- Vorhandene Crawling-Logik für "Sendung verpasst" in den neuen "Rubrik-Untermenüs" einsetzen

### ISSUE THREAD

**Issue by zxsd** [mediathekview/MSearch#65]
Betr.: [Entwicklung: Ohne git flow](https://github.com/mediathekview/MediathekView/wiki/Entwicklung:-Ohne-git-flowl)

**Überblick**
Dem Anschein nach könnte die vorhandene Crawling-Logik für die ZDF "Sendung verpasst" Offerierten vielleicht in den "Rubrik-Untermenüs" wiederverwendet werden. Aus Sicht eines Laien.

[Ergänzende Infos im MV-Forum lesen](http://zdfmediathk.sourceforge.net/forum/viewtopic.php?p=13301#p13301)

Ohne es vollkommen verstehen zu können, habe ich ein Blick auf das "Sendung verpasst" Angebot in der neuen ZDF Web-Präsenz geworfen. Dabei habe ich das Untermenü "Rubrik: Krimi" selektiert (grün im Bild). 

![zdf-krimi-rubrik](https://cloud.githubusercontent.com/assets/23268595/20519014/41b10afa-b06f-11e6-9056-0f6b4f2ce016.png)

Die Quelltext-Struktur in den "Rubrik"-Untermenüs scheint eng verwandt (wenn nicht gleich) als die Struktur in "Sendung verpasst" zu sein.  

![zdf-modus-sendungverpasst-und-rubrik_krimi](https://cloud.githubusercontent.com/assets/23268595/20519157/d09d5eee-b06f-11e6-9e27-e138f772547a.png)

Fazit ... könnte vielleicht die vorhandene Crawling-Logik für die "Sendung verpasst" Offerierten in den "Rubrik"-Untermenüs auch Verwendung finden?

Wenn schon, und nachdem es in Betrieb ist, dürfte die MV-Anpassung zur gegenwärtigen ZDF-Umstellung sicher als vollständig (eigentlich verbessert) betrachtet werden.  Ich nehme an, daß Crawler-Code-Anpassungen erforderlich wären. Wenn diese zu beträchtlich sind, pressiert das Issue aus meiner Sicht nicht.  Als sekundär/ergänzend sähe ich ein derartiges Rubrik-Untermenü Crawlen erst; das Crawling von "Sendung verpasst" hat jahrelang gut funktioniert.  Seit der ZDF-Umstellung wird aber der volle Umfang der ZDF-Offerierten offensichtlich nicht erfaßt.

Mir scheinen die Rubrik-Untermenüs als verwertbare Alternative zu den einzelnen Sendereihenseiten zu Crawlen.  Als ich nachschaute, habe ich durch diese Menüs, alle Sendungen/Episoden finden können, die als 'vermisst' von Usern in MV-Forum gemeldet wurden.  Als wesentliches Teil der umgestaltender ZDF-Webpräsenz empfiehlt sich diese vorgeschlagene Änderung/Erweiterung auch als 'Backup'-Fähigkeit ... wenn das ZDF das nächste mal 'was in der Live Infrastruktur ändert, mit Wirkung auf MV.  

Wenn sich die Anzahl der neu gefundene Sendungen als zu hoch bewiesen sollte, dann könnte das bestimmt geregelt werden ... aus Sicht eines Anwenders.

**Comment by Nicklas2751** [comment]
@zxsd
Bitte was?

Also zuerst was willst du uns mit dem Link zum Wiki sagen? "Btr.:" meinst du Betreff? Wenn ja hä? Das hat doch nix mit dem Inhalt dies Tickets zu tun und auch nicht mit der Ticket Erstellung.

So zum eigentlich Ticket. Mir wird auch nach mehrmaligem lesen nicht klar, was du möchtest bzw. was dich stört.

Das ist jetzt das 3. Ticket in folge bei dem ich nicht nachvollziehen kann was du uns sagen möchtest. Bitte kommentiere unter diesem Ticket doch mal mit einfache Worten was nicht passt und was du möchtest. So einfach wie möglich am besten mit konkreten Beispiel.

**Comment by Nicklas2751** [comment]
Btw. because i have seen you wrote for you in the USW. If it's easier for you to write in english you could do this maybe this help. ;)

**Comment by xaverW** [comment]
Versuch mal das zusammenzufassen, die Website der ZDF wird noch nicht komplett abgesucht
gefundene Filme:
altes Logfile: ZDF 18723
von heute:  ZDF  4328

jetzt wird nur der Teil abgesucht:
https://www.zdf.de/sendung-verpasst

es fehlt noch der Bereich der unter "Rubrik" zu finden fehlt, zB.:
https://www.zdf.de/sendungen-a-z

und die Benennung der Themen ist teils etwas unglücklich, passt nicht zu früher und den bereits angelegten Abos.
--> mal ins Forum schauen, da tauchen immer mal wieder Filme auf die beim ZDF noch fehlen

**Comment by Nicklas2751** [comment]
Aaah ok, super Danke. Jetzt ist das ganze etwas klarer.

**Comment by zxsd** [comment]
Der Reihe nach ...

> was willst du uns mit dem Link zum Wiki sagen?

Ich wollte deutlich machen, daß ich versucht hatte, mich am jetzigen Workflow anzupassen.  Eine Beschreibung wie eine Programm-Änderung von einem Bittsteller/Anwender einzureichen wäre, habe ich nicht finden können.  Und Gedanken kann ich nicht lesen.

> "Btr.:" meinst du Betreff? 

Nein.  Ich meinte "Betr." ... wie ich geschrieben habe ... und wie, laut [Duden](http://www.duden.de/rechtschreibung/Betr_), "Betreff" gängig abgekürzt ist. 

![betr](https://cloud.githubusercontent.com/assets/23268595/20558583/c480ddc8-b13e-11e6-813a-5748a806f8d1.PNG)


Ab und zu vergesse ich den Punkt hinzuzufügen; aber diesmal ist er dabei. Ich frage mich aber, warum so pingelig mir gegenüber?  Hoffentlich habe ich nicht ungewollt Feindseligkeit irgendwie verursacht.

> Wenn ja hä? Das hat doch nix mit dem Inhalt dies Tickets zu tun und auch nicht mit der Ticket Erstellung. 

Tja. Jetzt weiß ich Bescheid. Danke.
 
> So zum eigentlich Ticket. Mir wird auch nach mehrmaligem lesen nicht klar, was du möchtest bzw. was dich stört. 

Der Beitrag von @xaverW  hat das (viel besser, und vor allem viel kürzer) zusammengefaßt als ich es mir je zutrauen würde.  Irgendwie habe ich das Gefühl, aber, unterstreichen zu müssen mich stört nichts an MV.  Die Probleme die andere gemeldet haben stören mich nicht im Geringsten.  Ich möchte, daß MV halt weiter verbessert wird, und versuche dazu beizutragen. Mehr nicht.
 
> Das ist jetzt das 3. Ticket in folge bei dem ich nicht nachvollziehen kann was du uns sagen möchtest. Bitte kommentiere unter diesem Ticket doch mal mit einfache Worten was nicht passt und was du möchtest. So einfach wie möglich am besten mit konkreten Beispiel.

Der Beitrag von @xaverW  mußte als Erklärung ausreichen, oder? Was mir nicht passen würde, wäre von Dir als  Unruhestifter oder MV-Gegner betrachtet zu werden.  Das fände ich schade ... für uns beide.  Wie ich oben schon schrieb, möchte ich nur, "daß MV halt weiter verbessert wird, und versuche dazu beizutragen. Mehr nicht."

**Comment by Nicklas2751** [comment]
@zxsd 
Die Erklärung von @xaverW ist super. 
Um dich zu beruhigen nein keine Feindseligkeiten oder ähnliches. Und Problem meine ich nicht als Problem mit MV sondern ich meine damit was für ein Problem bei der Benutzung auftaucht also z.B. welcher programmatische Fehler bzw. Bug vorhanden ist. Und Ich rechne bei einem "Issue" zu einer Software hauptsächlich damit, dass jemand ein Problem hat was er gerne gelöst hätte. ;)

**Comment by zxsd** [comment]
> Btw. because i have seen you wrote for you in the USA. If it's easier for you to write in english you could do this maybe this help. 

Hhhmm.... MV wurde von Deutschen entwickelt, unter anderem das öffentlich-rechtliche, deutschsprachige Fernsehen weltweit leichter erreichbar werden zu lassen.  Alle MV-Anwender und Entwickler können Deutsch, meist als Muttersprache.  

Trotz meiner Schwierigkeiten und Schwächen, bleibe ich dabei.  Und hoffe daß meine Bemühungen, mit Kommunikations-Erfolg belohnt werden.

**Comment by zxsd** [comment]
Überholt _(deprecated_ auf Englisch) siehe https://github.com/mediathekview/MServer/issues/31.
