### ISSUE TITLE
Ruckelnde Streams

### ISSUE THREAD

**Issue by maxsz** [mediathekview/MSearch#66]
Mir ist heute aufgefallen, dass manche streams ein komisches Ruckelverhalten haben. 
Beispiel:
```
"Der Andere"
ZDF Mediathek URL: https://www.zdf.de/filme/der-fernsehfilm-der-woche/der-andere-100.html
Stream URL: https://nrodlzdf-a.akamaihd.net/none/zdf/16/11/161121_161121_sendung_fdw/2/161121_161121_sendung_fdw_2328k_p35v13.mp4
```

Hat jemand so etwas schon mal beobachtet?

**Comment by alex1702** [comment]
meinst du dass das video ruckelt?
wenn ja hat das nix mit mediathekview zu tun und betrifft eher den sender oder dich, dass dein pc zu langsam ist oder deine internetverbindung zu langsam ist.

**Comment by maxsz** [comment]
Das mp4 Video (Bild) von der Stream URL ist kaputt. Habe so etwas vorher noch nie gesehen. Auf der ZDF Seite spielt der m3u8 Stream ohne Probleme in höchster Qualität.

**Comment by alex1702** [comment]
dann muss es aber trotzdem an was anderem liegen, da mediathekview ja einfach nur die url von der seite raussucht. und bei mir spielt das video ohne probleme ab.

**Comment by zxsd** [comment]
> Das mp4 Video (Bild) von der Stream URL ist kaputt. Habe so etwas vorher noch nie gesehen. Auf der ZDF Seite spielt der m3u8 Stream ohne Probleme in höchster Qualität.

Die mp4-Datei wird nicht durch MV per [Streaming Verfahren](https://de.wikipedia.org/wiki/HTTP-Streaming) serviert.  Diese wird heruntergeladen; der Media-Player kommt mit Hilfe vom Puffern beim gleichzeitigen Abspielen (je nachdem) damit zu Recht.  Außerdem ist die Bildqualität der durch MV heruntergeladene Sendung deutlich besser als was man beim ZDF-Streaming kriegt, und verbraucht daher mehr Bandbreite.

Falls Dir das Erlebnis beim ZDF ausreichen tut, @maxsz, folgende Vorschlag ignorieren.  Wenn Du aber das MV-Erlebnis wieder versuchen willst, dann schlage ich vor, die Sendung vollständig runterzuladen.  Danach die Sendung erst abspielen.

**Comment by alex1702** [comment]
Ich denke es kann geschlossen werden, weil es nicht direkt Mediathekview betrifft. Falls doch noch klärungsbedarf ist, kann es ja wieder geöffnet werden.
