### ISSUE TITLE
Filme von KiKa landen doppelt in der FIlmliste

### ISSUE THREAD

**Issue by criztovyl** [mediathekview/MSearch#68]
Im Zusammenhang mit #45 habe ich bemerkt das die Filme anscheindend doppelt in der Liste landen und nocheinmal in MediathekView rausgefiltert werden. Soweit ich erkennen konnte, sind die doppeten Filme in der Filmliste identisch.

Ich weiß nicht ob das ein Bug ist in der Lösung die doppelten Filme so rauszufiltern ist  oder obs so gewollt ist.

Jedenfalls kann mit #45 in MediathekView eigentlich keine solche Filterung mehr stattfinden, es sollten durch den Crawler die Filme "einfach" nicht doppelt in die Liste eingehen.

**Comment by xaverW** [comment]
im mediathekreader.addFilm wird doch geprüft, ob die URL schon in der neuen Liste ist?? Weiß nicht genau was du meinst.

**Comment by xaverW** [comment]
ich habe jetzt zB. 2 gefunden:
Trio - Cyber Gold
Trio - Cyber-Gold

der Rest ist gleich aber das Thema unterscheidet sich durch den "-"

hast du mal eine Beispiel? Der Index zum Vergleich ist Sender - Thema - URL

**Comment by criztovyl** [comment]
Hm, ich hatte den ABC Bär, 81. Folge. Ich hoffe ich habe nicht den Bindestrich übersehen oder was in MSearch übersehen.

**Comment by xaverW** [comment]
doch. Ist aber trotzdem nicht ganz OK, kommt aber vom Crawler

beim KiKa wird da gesucht:
http://www.kika.de/sendungen/sendungenabisz100.html
http://www.kika.de/videos/allevideos/allevideos-buendelgruppen100.html

das Thema wird aus dem <title> tag genommen:
http://www.kika.de/abc-baer/sendereihe1876.html
http://www.kika.de/abc-baer/sendungen/allevideosabcbaer100.html

und da wird das unterschiedlich geschrieben (wohl gemerkt für die gleiche Sendung!)

das muss irgendwie geändert werden.

**Comment by Nicklas2751** [comment]
Ein ähnliches verhalten konnte ich beim ZDF mit der heute-show feststellen. Mal wird das unter heute-show und mal unter heute show veröffentlicht.

**Comment by xaverW** [comment]
aktuelle Sachen? Das sollte geändert sein.

**Comment by Nicklas2751** [comment]
Ja aktuell.

**Comment by xaverW** [comment]
habe KiKa versucht zu ändern, war aber gar nicht so einfach möglich. Bei allen Tags, ... aus denen sich das Thema auslesen ließ, klappte es bei dem einen und anderen Thema nicht.
habe dann einfach manuelle den ABC-Bär angepasst.
->heute show: der aktuelle Crawler findet nur: heute-show
