### ISSUE TITLE
Vergleichswert in Filmliste aufnehmen?

### ISSUE THREAD

**Issue by criztovyl** [mediathekview/MSearch#72]
Ich würde in `DatenFilm` ein Feld `FILM_HASH` hinzufügen, das dann einen einfachen, nicht-kryptographischen Hash enthält, deren Inhalt der MediathekReader entsprechend zusammensetzt, was dann den Vergleich der URL ersetzten sollte. 
`DatenFilm#getIndex` würde dann aus Sender, Titel, Thema & Hash statt Sender, Thema & (angepasster) URL zusammengesetzt werden.

Das würde das Problem (einfach) lösen, das bspw. [hier](https://github.com/mediathekview/MSearch/blob/develop/src/main/java/mSearch/daten/DatenFilm.java#L304) in `DatenFilm` `MediathekOrf` entfernt werden kann, was wiederum für die Entflechtung von Crawler- und Nicht-Crawler-Code notwendig ist.

**Comment by Nicklas2751** [comment]
> 'Ich würde in DatenFilm ein Feld FILM_HASH hinzufügen, das dann einen einfachen, nicht-kryptographischen Hash enthält, deren Inhalt der MediathekReader entsprechend zusammensetzt, was dann den Vergleich der URL ersetzten sollte.
> DatenFilm#getIndex würde dann aus Sender, Titel, Thema & Hash statt Sender, Thema & (angepasster) URL zusammengesetzt werden.
> 
> Das würde das Problem (einfach) lösen, das bspw. hier in DatenFilm MediathekOrf entfernt werden kann, was wiederum für die Entflechtung von Crawler- und Nicht-Crawler-Code notwendig ist.'
> 

Das klingt gut.

**Comment by criztovyl** [comment]
Heh, warum ein Zitat? :D

**Comment by Nicklas2751** [comment]
Ich dachte das wäre der gleiche issue. Schreiben ne grad via Mail da ist das nicht so eindeutig. ^^

**Comment by zxsd** [comment]
> ein Feld FILM_HASH hinzufügen, das dann einen einfachen, nicht-kryptographischen Hash enthält

Ich will nicht stören, aber ist ein derartiger Wert nicht irgendwo schon vorhanden, der ggf. wiederverwendet werden könnte?  ...

Ab [hier in MV-Forum](http://zdfmediathk.sourceforge.net/forum/viewtopic.php?f=2&t=665&hilit=hashwert&start=19) Beitrag basiert sich obige Frage.

Anmerkung. Inzwischen ist der Wert "%Z" geworden ("%z" mitsamt Suffix/Dateiendung), und bei WDR indirekten DLs funzt diese Funktionalität nicht richtig.

**Comment by criztovyl** [comment]
Du störst nicht.

Die Methode/Funktion die dort verwendet wird, lässt sich sicher wiederverwenden, aber das Prinzip nicht.

Denn dort wird in MV (nicht MSearch) auf einem bereits vorhandenem Eintrag der Filmliste gearbeitet, das Ziel hier ist aber hier in MSearch einen neuen Wert in die Liste mit aufzunehmen, der es in MV möglich macht zu erkennen ob der Listeneintrag so schon vorhanden ist, ohne spezielle Regeln bspw für die URL beachten zu müssen. (Wobei auch MSearch in seiner Rolle als Crawler das nachguckt, um die vorhandene Filmliste zu erweitern.)

**Comment by xaverW** [comment]
ich halte dass jetzt nicht für eine gute Idee, das kann man ja mal im Hinterkopf behalten (außerdem gibt es so was ähnliches schon: DatenFilm.FILM_URL_HISTORY). Nur um ein paar Konstanten in der Lib zu sparen, jetzt einfach mal die Filmliste wieder erweitern und damit auch wieder vergrößern.

**Comment by criztovyl** [comment]
Was steht denn in `FILM_URL_HISTORY`?

**Comment by criztovyl** [comment]
Ah, ich glaub ich hab's verstanden.
`#GetUrl` sollte also statt `FILM_URL` `FILM_URL_HISTORY` nehmen, falls vorhanden?

**Comment by xaverW** [comment]
da steht das, was in die Datei history.txt geschrieben wird (sind dann die grau hinterlegten Zeilen). Ist das Feld leer, wird die normale URL geschrieben.

**Comment by criztovyl** [comment]
Wie kompliziert wäre es den Namen des Feldes `FILM_URL_HISTORY` umzubenennen u./o. die Funktion davon zu ändern?

Ich denke hier daran das wir dadurch möglw. die Vergleichsarbeit die `ListeFilme#updateListe` leisten muss minimieren könnten, wenn in `FILM_URL_HISTORY` der o.g. Hash einfügt wird und dann nur noch der verglichen werden muss, statt 4 Strings also nur einer.
Vllt sollte der Hash dann auch doch kryptografisch sein, um unnötige Kollisionen zu vermeiden.

Den Hash sollte dann der Crawler errechnen, je nach dem wie er das als grad' sinnvoll erachtet, in dem er bspw. für KIKA und ORF nur 'nen Teil der URL für den Hash mit in Betracht zieht. Zusammensetzen sollte sich der Hash dann mind. aus Sender, Titel, Thema und (angepasster) URL.

So ganz naiv würde dann der Aufbau des HashSet in `#updateListe` in etwa so aussehen (hier für's ersetzen, wenn nicht ändert sich ja nur die Liste über die iteriert wird.):
```java
for (DatenFilm f : listeEinsortieren) {
    hash.add(f.arr[DatenFilm.FILM_IDENTITY]); // *whooo*
}
```
([Vorher](https://github.com/mediathekview/MSearch/blob/56c25ce1764f251df73d1e62d8b1e30f1463cbf6/src/main/java/mSearch/daten/ListeFilme.java#L98))
