### ISSUE TITLE
SRF: \u0026

### ISSUE THREAD

**Issue by simon04** [mediathekview/MSearch#75]
Einige Einträge des SRF enthalten den Titel "Glanz \u0026 Gloria".
![2016-11-27-22-47-49-001](https://cloud.githubusercontent.com/assets/782446/20652126/bbf1b20a-b4f3-11e6-8fe7-b506820818f2.png)

Ein Auszug aus der JSON-Datei:
```
  "X" : [ "", "", "«Glanz \\u0026 Gloria» mit Waldmensch und Annina Frey beim Hornussen", "28.07.2016", "18:42:02", "00:13:02", "100", "Tarzan: Neues vom Waldmenschen / Annina Frey: Kampf mit dem Nouss", "http://podcastsource.sf.tv/nps/100793309/782.12/%C2%ABGlanz+%26+Gloria%C2%BB+mit+Waldmensch+und+Annina+Frey+beim+Hornussen/podcast/glanzundgloria/2016/07/glanzundgloria_20160728_184202_v_podcast_h264_q10.mp4", "http://www.srf.ch/sendungen/glanz-und-gloria", "https://ws.srf.ch/subtitles/urn:srf:ais:video:eeda56cf-be11-49e4-9558-27c955980a8b/subtitle.ttml", "", "", "", "31|352688083/782.12/%C2%ABGlanz+%26+Gloria%C2%BB+mit+Waldmensch+und+Annina+Frey+beim+Hornussen/podcast/glanzundgloria/2016/07/glanzundgloria_20160728_184202_v_podcast_h264_q30.mp4", "", "1469724122", "", "", "false" ],
```

**Comment by zxsd** [comment]
Wie obiges Bild verdeutlicht, ist derartiges Alt-Encoding alles anderes als konsequent seitens SRF implementiert.  Diese Zeichenkette (und andere "\u"-basierten Alt-Encoding, wie "\u0026") kommen immer wieder im Feld "Titel" in einigen SRF-Sendereihen vor (siehe unten, mir stört's kaum).

Eine konsequente Anwendung von Alt-Encoding (allerdings die Web-übliche Art, "&string;") ist immer in den originalen Untertitel-Dateien von ORF zu sehen, zur Zeit die TTML-Version. Die jetzige SRT-Dateien, welche aus diese TTML-Dateien durch Code vom @derreisende77 konvertiert werden, weisen die 'normalen' Zeichen auf.  Eventuell könnte Portionen vom @derreisende77s Code in diesem Fall eingesetzt werden. (... aus Sicht eines Anwenders) 

![srf-alt-encoding1](https://cloud.githubusercontent.com/assets/23268595/20657499/598eff30-b504-11e6-9aa4-3efff87d5a03.PNG)

**Comment by Nicklas2751** [comment]
Das ist ein Anzeige Fehler und gehört somit in Mediathekview. In der Liste ist das so kein Problem aber bei der Anzeige sollten die Unicode Zeichen wieder als solche angezeigt werden. Ich habe das Ticket entsprechend umgezogen: https://github.com/mediathekview/MediathekView/issues/164

**Comment by lookshe** [comment]
Ich denke, es ist falsch das hier zu schließen und in die Anzeige zu verschieben, denn die Anzeige stellt einfach nur dar, was in der Filmliste steht. Und letztlich wurde in die Filmliste etwas falsches eingetragen. Ich habe gerade über die letzte Liste des Crawlers gesucht und es sind erstaunlich wenig Filme (83) mit diesem Problem drin und zudem finden sich die selben Einträge auch mit korrekten Unicode-Zeichen. Ich denke hier pfuscht evtl. ein (alter) Crawler dazwischen, bei dem der Server nicht sauber auf Unicode konfiguriert war/ist.

**Comment by zxsd** [comment]
> hier pfuscht evtl. ein (alter) Crawler dazwischen

Mag _auch_ stimmen, aber ich kann versichern daß das Verhalten schon lange bei SRF vorhanden ist ... und ohne erkennbares Muster:

![srf-alt-encoding2](https://cloud.githubusercontent.com/assets/23268595/20736996/18b4cd58-b678-11e6-86d2-c1fed38f68cc.PNG)

**Comment by Nicklas2751** [comment]
Ich denke eher, dass das ein Fehler seitens der Sender ist bzw. sie mal die Codierung mit \u nutzen und mal nicht. Und da der Crawler aus einem \ richtigerweise \\ macht wird dies direkt so angezeigt. Daher gehört es für mich in die Anzeigelogik aus einem \\u wieder \u zu machen denn der Crawler passt ja nur ist es in der Anzeige eher unschön.

Um sicher zu gehen ob es nicht ein veralteter Crawler ist werde ich dann mal nen aktuellen MSearch laufen lassen und gucken ob er Texte mit \u findet.

**Comment by derreisende77** [comment]
Nein es ist kein Fehler der Sender. Es ist korrekt das Ampersand als \u0026 zu kodieren. Der Fehler liegt in MSearch bei decoden der strings.
Ich habe es gefixt. Es ist kein Fehler in MV.
Es bleibt zu überlegen ob man den Fix aus FilmlisteLaden direkt im Server implementiert anstatt jeweils beim Laden die Verarbeitung zu verzögern.

**Comment by derreisende77** [comment]
wurde mit commit in MSearch gefixt. Anzeige in MV nun korrekt.

**Comment by xaverW** [comment]
gehört in MSearch, dafür gibts schon eine Funktion, habs da eingefügt.
bei mir war dann nichts mehr davon in der Filmliste.
