### ISSUE TITLE
Qualität hochsetzen bei ARD?

### ISSUE THREAD

**Issue by claell** [mediathekview/MSearch#81]
Mir ist aufgefallen, dass seit einiger Zeit bei der ARD teils kein HD mehr gefunden wird.

Aufgefallen war mir das bei der Sendung "Die Pfefferkörner".

Nun ist es auch bei der Sendung "Der Tatortreiniger" der Fall.

Beispiel: http://media.ndr.de/progressive/2016/1212/TV-20161212-1510-5800.hq.mp4

Es geht aber auch: http://media.ndr.de/progressive/2016/1212/TV-20161212-1510-5800.hd.mp4 was aber in MV nicht verfügbar ist.

**Comment by Nicklas2751** [comment]
MServer ist dafür zuständig. Hier wurde es auch bereits reportet: https://github.com/mediathekview/MServer/issues/37

**Comment by claell** [comment]
Oh alles klar, danke für den Hinweis.
Ist MSearch nicht der Crawler oder warum wird das jetzt in MServer gemacht?

**Comment by Nicklas2751** [comment]
Ne MSearch ist nicht mehr der Crawler, das war mal. MServer ist jetzt Crawler und Server und MSearch ist nurnoch eine Lib. Muss nurnoch umbenannt werden. ;)

**Comment by claell** [comment]
Ah, alles klar.
