### ISSUE TITLE
error: package javafx.collections does not exist

### ISSUE THREAD

**Issue by martinkg** [mediathekview/MSearch#87]
Hallo,

ich versuche gerade das aktuelle MSearch aus dem git auf Fedora 25 zu kompilieren, scheitere
aber mit den folgenden Meldungen:

`/home/martin/rpmbuild/BUILD/MSearch-3467040e54e31625425eb33dcd0f20a8da575dc4/src/main/java/mSearch/tool/SysMsg.java:22: error: package javafx.collections does not exist
import javafx.collections.FXCollections;
                         ^
/home/martin/rpmbuild/BUILD/MSearch-3467040e54e31625425eb33dcd0f20a8da575dc4/src/main/java/mSearch/tool/SysMsg.java:23: error: package javafx.collections does not exist
import javafx.collections.ObservableList;
                         ^
/home/martin/rpmbuild/BUILD/MSearch-3467040e54e31625425eb33dcd0f20a8da575dc4/src/main/java/mSearch/tool/SysMsg.java:27: error: cannot find symbol
    public static ObservableList<String> textSystem = FXCollections.observableArrayList();
                  ^
  symbol:   class ObservableList
  location: class SysMsg
/home/martin/rpmbuild/BUILD/MSearch-3467040e54e31625425eb33dcd0f20a8da575dc4/src/main/java/mSearch/tool/SysMsg.java:28: error: cannot find symbol
    public static ObservableList<String> textProgramm = FXCollections.observableArrayList();
                  ^
  symbol:   class ObservableList
  location: class SysMsg
/home/martin/rpmbuild/BUILD/MSearch-3467040e54e31625425eb33dcd0f20a8da575dc4/src/main/java/mSearch/tool/SysMsg.java:126: error: cannot find symbol
    private synchronized static void addText(ObservableList<String> text, String texte) {
                                             ^
  symbol:   class ObservableList
  location: class SysMsg
/home/martin/rpmbuild/BUILD/MSearch-3467040e54e31625425eb33dcd0f20a8da575dc4/src/main/java/mSearch/tool/SysMsg.java:27: error: cannot find symbol
    public static ObservableList<String> textSystem = FXCollections.observableArrayList();
                                                      ^
  symbol:   variable FXCollections
  location: class SysMsg
/home/martin/rpmbuild/BUILD/MSearch-3467040e54e31625425eb33dcd0f20a8da575dc4/src/main/java/mSearch/tool/SysMsg.java:28: error: cannot find symbol
    public static ObservableList<String> textProgramm = FXCollections.observableArrayList();
                                                        ^
  symbol:   variable FXCollections
  location: class SysMsg
7 errors
:compileJava FAILED
`
Da Fedora eine rpm basiende Distri ist, kompiliere ich MSearch mit folgender rpm spec Datei:
[MSearch.spec](https://martinkg.fedorapeople.org/Packages/MediathekView/MSearch.spec)

openjfx habe ich aus folgender src.rpm Datei kompiliert:
[openjfx-8.0.152-3.b00.fc25.src.rpm](https://jonny.fedorapeople.org/openjfx-8.0.152-3.b00.fc25.src.rpm)

Das Paket openjfx beinhaltet folgende Dateien:
`/usr/lib/jvm/openjfx
/usr/lib/jvm/openjfx/bin
/usr/lib/jvm/openjfx/bin/javafxpackager
/usr/lib/jvm/openjfx/bin/javapackager
/usr/lib/jvm/openjfx/javafx-src.zip
/usr/lib/jvm/openjfx/lib
/usr/lib/jvm/openjfx/lib/ant-javafx.jar
/usr/lib/jvm/openjfx/lib/javafx-mx.jar
/usr/lib/jvm/openjfx/lib/packager.jar
/usr/lib/jvm/openjfx/rt
/usr/lib/jvm/openjfx/rt/lib
/usr/lib/jvm/openjfx/rt/lib/amd64
/usr/lib/jvm/openjfx/rt/lib/amd64/libdecora_sse.so
/usr/lib/jvm/openjfx/rt/lib/amd64/libglass.so
/usr/lib/jvm/openjfx/rt/lib/amd64/libjavafx_font.so
/usr/lib/jvm/openjfx/rt/lib/amd64/libjavafx_font_freetype.so
/usr/lib/jvm/openjfx/rt/lib/amd64/libjavafx_font_pango.so
/usr/lib/jvm/openjfx/rt/lib/amd64/libjavafx_iio.so
/usr/lib/jvm/openjfx/rt/lib/amd64/libprism_common.so
/usr/lib/jvm/openjfx/rt/lib/amd64/libprism_es2.so
/usr/lib/jvm/openjfx/rt/lib/amd64/libprism_sw.so
/usr/lib/jvm/openjfx/rt/lib/ext
/usr/lib/jvm/openjfx/rt/lib/ext/jfxrt.jar
/usr/lib/jvm/openjfx/rt/lib/javafx.properties
/usr/lib/jvm/openjfx/rt/lib/jfxswt.jar
/usr/share/doc/openjfx
/usr/share/doc/openjfx/README
/usr/share/doc/openjfx/README.fedora
/usr/share/licenses/openjfx
/usr/share/licenses/openjfx/LICENSE
/usr/share/man/ja_JP.UTF-8/man1/javafxpackager.1.gz
/usr/share/man/ja_JP.UTF-8/man1/javapackager.1.gz
/usr/share/man/man1/javafxpackager.1.gz
/usr/share/man/man1/javapackager.1.gz

[root@fc25 tmp]# java -version
openjdk version "1.8.0_121"
OpenJDK Runtime Environment (build 1.8.0_121-b14)
OpenJDK 64-Bit Server VM (build 25.121-b14, mixed mode)`

**Comment by Nicklas2751** [comment]
Ich würde versuchen ein bereits für Fedora kompilierte OpenJFX Version zu versuchen und wenn das nicht klappt es mal direkt mit der passenden Oracle JDK versuchen.

**Comment by martinkg** [comment]
Nachdem ich die erforderlichen Links angelgt habe und die rpm spec-Datei angepasst habe kompiliert es durch

 `#!/bin/bash

openjfx_dir=/usr/lib/jvm/openjfx

jdk_files=$(find $openjfx_dir/{bin,lib} -type f -print)
for file in $jdk_files; do
  relative=${file#$openjfx_dir/}
  ln -sfv "$openjfx_dir/$relative" "/usr/lib/jvm/java/$relative"
done

jre_files=$(find $openjfx_dir/rt -type f -print)
for file in $jre_files; do
  relative=${file#$openjfx_dir/rt/}
  ln -sfv "$openjfx_dir/rt/$relative" "/usr/lib/jvm/jre/$relative"
done`
